package com.diffblue.deeptestutils;

import org.junit.Assert;
import org.junit.rules.ExpectedException;
import org.junit.Test;

import java.lang.reflect.Array;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

import com.diffblue.deeptestutils.CompareWithFieldList;
import com.diffblue.deeptestutils.Reflector;

public class FieldListTest {

  @org.junit.Rule
  public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: FieldList */


  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */

  @org.junit.Test
  public void com_diffblue_deeptestutils_FieldList__init__000_4e79fa610e40b282() throws Throwable {

    com.diffblue.deeptestutils.FieldList instance;
    {
      /* Arrange */

      /* Act */
      /* Creating object to test constructor */
      instance = new com.diffblue.deeptestutils.FieldList();

      /* Method return type is void, or not expected to return */
    }
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */

  @org.junit.Test
  public void com_diffblue_deeptestutils_FieldList_add_000_9cae649fc599ee79() throws Throwable {

    {
      /* Arrange */
      com.diffblue.deeptestutils.FieldList param_4 = (com.diffblue.deeptestutils.FieldList) Reflector.getInstance("com.diffblue.deeptestutils.FieldList");
      java.util.ArrayList arrayList = new java.util.ArrayList();
      Reflector.setField(param_4, "fields", arrayList);
      String name = null;
      Object value = null;

      /* Act */
      param_4.add(name, value);
    }
  }
}
