addons:
  apt:
    packages:
      - openjdk-7-jdk

language: java

matrix:
  include:
  - jdk: openjdk7
  - jdk: openjdk8
  - jdk: oraclejdk8
  - jdk: openjdk11
  - jdk: oraclejdk11

install:
  - mvn -version
